/**
 * 可公开的项目身份与同步来源。项目根目录按当前仓库的父目录解析；
 * PROJECT_WORKSPACE_ROOT 可在本机覆盖，绝对路径不会进入 Git 或公开投影。
 */
export const projectCatalog = [
  {
    directory: "personal-sites",
    documents: [
      "README.md",
      "PRODUCT.md",
      "DESIGN.md",
      "docs/frontend-architecture.md",
      "docs/project-practice-sync.md",
      "docs/supabase-x-sync.md",
    ],
    id: "personal-sites",
    memoryDirectories: ["personal-sites"],
    order: 1,
    period: "2026 — 至今",
    repo: "https://github.com/defulat-coder/personal-sites",
    review: {
      currentFocus: "验证项目级增量同步在更多仓库上的稳定性与内容质量，并把已批准项目档案持续纳入站内阅读和检索。",
      overrides: {
        "motion-migration": {
          title: "按动效语义选择 CSS、Motion 与 WAAPI",
        },
        "project-practice-sync-design": {
          kind: "capability",
          status: "已上线",
          summary: "按稳定 projectId 从 Git、项目文档与 Codex 工作记录生成内容摘要增量，经过本机私有草稿、显式审核和敏感信息闸门后，原子发布到本地 SQLite 公开快照。",
          title: "项目实践增量同步",
        },
        "x-curation-sqlite-projection": {
          kind: "milestone",
          status: "已演进",
          summary: "X 书签与点赞经过本机抓取、AI 解析和公开字段投影；当前线上读取随部署打包的 SQLite，本机敏感队列与凭据不进入网站或 Git。",
          title: "X 策展公开投影演进",
        },
      },
      summary: "一个持续更新的 Agent 工程档案：将每日输入、项目能力、实验、决策与实践组织为可追溯的公开内容，并让原始资料、审核草稿和线上投影保持严格边界。",
    },
    role: "独立设计与开发",
    shots: [
      { label: "每日动态", src: "/images/works/personal-site/feed.jpg" },
      { label: "推特点赞", src: "/images/works/personal-site/curation.jpg" },
      { label: "开源关注", src: "/images/works/personal-site/open-source.jpg" },
      { label: "问一问", src: "/images/works/personal-site/ask.jpg" },
    ],
    slug: "personal-site",
    stack: ["Next.js", "React", "TypeScript", "SQLite", "sqlite-vec", "Supabase", "Kimi", "Vercel"],
    status: "持续维护",
    summary: "一个持续更新的 Agent 工程档案：把每日输入、项目实践与可追溯判断组织成公开内容，同时严格隔离本机敏感资料。",
    title: "这个站点本身",
    url: "https://default-coder.lovemyrmb.cn/",
  },
  {
    directory: "pi-samples",
    documents: ["README.md", "knowledge/README.md"],
    id: "pi-samples",
    memoryDirectories: ["pi-samples"],
    order: 2,
    period: "2026 — 至今",
    repo: "https://github.com/defulat-coder/pi-samples",
    review: { overrides: {} },
    role: "Agent 运行时实验与全栈开发",
    shots: [],
    slug: "pi-workbench",
    stack: ["Pi Coding Agent", "TypeScript", "React", "Fastify", "SQLite", "Docker"],
    status: "持续试验",
    summary: "一个以 Pi Coding Agent 为核心的 Web Agent Workbench，用真实运行验证 session、工具、知识检索、事件流与业务数据交互。",
    title: "Pi Workbench",
  },
  {
    directory: "waker",
    documents: ["README.md", "platform/README.md", "CONTEXT.md"],
    id: "waker",
    memoryDirectories: ["waker", "waker-source"],
    order: 3,
    period: "2026 — 至今",
    repo: "https://github.com/defulat-coder/agent-waker",
    review: { overrides: {} },
    role: "架构研究与平台工程",
    shots: [],
    slug: "waker",
    stack: ["TypeScript", "Bun", "Workflow", "MCP", "SQLite", "Docker"],
    status: "持续构建",
    summary: "围绕长周期 Agent 工作流、权限、上下文快照和可恢复执行构建的平台，并用恢复参考与权威验证约束实现。",
    title: "Waker Platform",
  },
];
